spring.application.name=meal-planner
#logging.level.org.springframework.boot.autoconfigure=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/meal_planner
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.profiles.active=dev

jwt.secret=Z@5yK8m#N9vL2qW1xT4eRg7BfU0cXdV3

